=== Bigsby/flow/puzzles/puzzle.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "title": "Puzzle data specefication",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "name": {
            "type": "string",
            "minLength": 1
        },
        "subtitle": {
            "type": "string"
        },
        "positions": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/position"
            }
        },
        "colours": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/colour"
            }
        },
        "solution": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/solution"
            }
        }
    },
    "required": [
        "name",
        "subtitle",
        "positions",
        "colours"
    ],
    "$defs": {
        "position": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "positions": {
                    "$ref": "#/definitions/positions"
                },
                "type": {
                    "$ref": "#/definitions/positionType"
                }
            },
            "required": [
                "positions",
                "type"
            ]
        },
        "colour": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "e1": {
                    "$ref": "#/definitions/point"
                },
                "e2": {
                    "$ref": "#/definitions/point"
                }
            },
            "required": [
                "e1",
                "e2"
            ]
        },
        "solution": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/positions"
            }
        }
    },
    "definitions": {
        "point": {
            "type": "string",
            "pattern": "[0-9]+,[0-9]+"
        },
        "positions": {
            "type": "string",
            "pattern": "^[0-9]+(-[0-9]+)?,[0-9]+(-[0-9]+)?$"
        },
        "positionCoordinate": {
            "type": "string",
            "pattern": "^[0-9]+(-[0-9]+)?$"
        },
        "positionType": {
            "type": "string",
            "pattern": "^NONE$|^(UP|DOWN|LEFT|RIGHT|BRIDGE|UPLEFT|UPRIGHT|DOWNLEFT|DOWNRIGHT)((\\s?(,|\\|)\\s?)(UP|DOWN|LEFT|RIGHT|BRIDGE|UPLEFT|UPRIGHT|DOWNLEFT|DOWNRIGHT))*$"
        }
    }
}

=== Bigsby/flow/puzzles/flow/01 - Intro/01 - Classic Pack/03 - 7x7 - medium/028.json
{
    "$schema": "../../../../puzzle.schema.json",
    "name": "28",
    "subtitle": "7x7",
    "positions": [
        {
            "positions": "0,0",
            "type": "LEFT | UP"
        },
        {
            "positions": "6,0",
            "type": "RIGHT | UP"
        },
        {
            "positions": "0,6",
            "type": "LEFT | DOWN"
        },
        {
            "positions": "6,6",
            "type": "RIGHT | DOWN"
        },
        {
            "positions": "0,1-5",
            "type": "LEFT"
        },
        {
            "positions": "1-5,0",
            "type": "UP"
        },
        {
            "positions": "6,1-5",
            "type": "RIGHT"
        },
        {
            "positions": "1-5,6",
            "type": "DOWN"
        },
        {
            "positions": "1-5,1-5",
            "type": "NONE"
        }
    ],
    "colours": [
        {
            "e1": "5,1",
            "e2": "3,3"
        },
        {
            "e1": "5,0",
            "e2": "1,6"
        },
        {
            "e1": "2,0",
            "e2": "4,3"
        },
        {
            "e1": "0,1",
            "e2": "3,2"
        },
        {
            "e1": "1,4",
            "e2": "0,6"
        },
        {
            "e1": "0,4",
            "e2": "5,5"
        },
        {
            "e1": "0,0",
            "e2": "3,1"
        }
    ],
    "solution": [
        [
            "3,3",
            "3-5,4",
            "5,1-3"
        ],
        [
            "5,0",
            "1-5,6",
            "6,0-6"
        ],
        [
            "2-4,0",
            "4,1-3"
        ],
        [
            "0,1-2",
            "1-3,2"
        ],
        [
            "0,5-6",
            "1,4-5"
        ],
        [
            "0,4",
            "0-2,3",
            "2,4",
            "2-5,5"
        ],
        [
            "0-1,0",
            "1-3,1"
        ]
    ]
}
